services:
  nginx:
    container_name: nginx
    image: nginx:alpine  # Use the Nginx image
    ports:
      - "8000:80"  # Map port 8000 on the host to port 80 inside the container
    volumes:
      - ./:/var/www  # Mount the Laravel application directory
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Use a custom Nginx config
    depends_on:
      - app  # Ensure PHP-FPM is started before Nginx
    networks:
      - laravel-network  # Connect to the custom network

  app:
    container_name: app
    build: .  # Build from the Dockerfile (assumed to be a PHP-FPM setup)
    depends_on:
      - db  # Wait for the database to be ready
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www  # Mount the Laravel application directory
    networks:
      - laravel-network  # Connect to the custom network

  db:
    container_name: chat_db
    image: mysql:8  # Use MySQL version 8
    restart: always
    ports:
      - "3305:3306"  # Expose MySQL on port 3305
    environment:
      MYSQL_DATABASE: chat_app2  # Create the 'chat_app' database
      MYSQL_ROOT_PASSWORD: root  # Set the root password for MySQL
    volumes:
      - chat_app2:/var/lib/mysql  # Persist MySQL data
    networks:
      - laravel-network  # Connect to the custom network

  node:
    container_name: websocket_node
    image: node:22
    working_dir: /var/www
    volumes:
      - ./:/var/www  # Mount the Laravel application directory
    tty: true
    ports:
      - "5173:5173"  # For Vite development server
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm install && npm run dev"
    networks:
      - laravel-network  # Use the same network as other services

# Define the custom network
networks:
  laravel-network:
    driver: bridge

# Define the volume for MySQL data persistence
volumes:
  chat_app2:
